# Generated by Django 2.2.4 on 2020-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsandcommodities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
