# Generated by Django 2.2.4 on 2020-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(max_length=2000)),
                ('change', models.CharField(max_length=100)),
                ('change_perc', models.CharField(blank=True, max_length=250, null=True)),
                ('high', models.FloatField(blank=True, max_length=100, null=True)),
                ('low', models.FloatField(blank=True, max_length=100, null=True)),
                ('latestVolume', models.CharField(blank=True, max_length=1000, null=True)),
                ('exchange', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_loser', models.BooleanField(default=False)),
                ('is_gainer', models.BooleanField(default=False)),
            ],
        ),
    ]
