# Generated by Django 2.2.4 on 2020-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
