# Generated by Django 2.2.4 on 2020-03-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
