# Generated by Django 3.0.5 on 2020-04-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200329_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pred_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
